KnpLabs/KnpTimeBundle

README.markdown
Hi guys!
Super minor README tweak! (WOW)
Cheers!
=> Several README tweaks

Resources/translations/time.uk.xliff
Bug with showing time, ending on 1 (21, 31 ... 91 etc).
When the difference in the 21 days between the dates we get:
Before: "через 1 день", "1 день тому".
After: "через 21 день", "21 день тому".
=> Bug with showing time, ending on 1.

README.md
Because there's some confusion on who maintains the library, I added this section and listed myself. I like this library, so would be happy to be a maintainer.
@akovalyov you seem like an obvious maintainer also - should I add you?
Cheers!
=> Adding a maintainers section

Resources/translations/time.cs.xliff
Fix issues with Czech translation.
=> Fix czech translation

Resources/translations/time.bs_Latn_BA.xliff, Resources/translations/time.hr_HR.xliff, Resources/translations/time.sr_Latn.xliff, Resources/translations/time.tr.xliff
we are using this bundle in our project, i will send pr when we add extra translation.
=> add some Turkish related translations

Resources/translations/time.ca.xliff
Related with the Issue #90 
Created a new file 'time.ca.xliff' that contains all the translations available in the version 1.7.0.
=> NewFeature: Catalan Translations

README.md
"I don't give an ass about having a badge on my readme"
- Ryan Weaver
=> Remove the ugly badge

Resources/translations/time.eo.xliff
Hello, I just added an Esperanto translation that I need for my project. 
Thanks!
=> added Esperanto translation

Resources/translations/time.bg.xliff
=> Add bg translation

.gitignore, Tests/IntegrationTest.php, phpunit.xml.dist
At the moment no tests are run due to different path capitalisation.
=> Fixed phpunit tests path

DateTimeFormatter.php, Tests/IntegrationTest.php, Tests/fixtures/templateSpecificLocale.twig, Twig/Extension/TimeExtension.php
=> added the locale parameter

.travis.yml, README.md, Tests/IntegrationTest.php, Tests/fixtures/templateSpecificLocale.twig
=> updating README for locale override

translations/time.nb.xliff
This adds the #181 duration translation for "Norsk bokmål" NB locale
=>  Updated duration translation for NB

translations/time.ru.xliff
Per @Kartulin in https://github.com/KnpLabs/KnpTimeBundle/issues/181#issuecomment-1659025685
=> minor: ru duration translations

translations/time.es.xliff
Add spanish translations requested in #181 😀
=> minor: es duration translations

translations/time.fr.xliff
#181 add missing FR translations
=> minor: Add missing FR translations 

translations/time.de.xliff
This PR adds missing German translations for #181
=> minor: de duration translations

translations/time.nl.xliff
#181 Add NL duration translations
=> minor: Update time.nl.xliff

translations/time.pl.xliff
Related to https://github.com/KnpLabs/KnpTimeBundle/issues/181
=> Update polish translations to be up-to-date

translations/time.de.xliff
https://github.com/KnpLabs/KnpTimeBundle/issues/196
=> trans: add german translation for 'age'

README.md
i think this change helps to make it better readable.
=> docs: improve example in README.md

translations/time.it.xliff
Updated italian translations.
#196 and #181
=> trans: Update italian translations

.gitattributes, src/DateTimeFormatter.php
Hi @weaverryan, seems like there are some missing entries in the gitattributes file.
=> Add missing entries to .gitattributes

.github/workflows/ci.yaml
=> [ci] test against symfony 7

translations/time.sk.xliff
Added slovak translations for duration
=> [translation] add additional Slovak translations
