KnpLabs/KnpTimeBundle

Twig/Extension/TimeExtension.php

This extension has relied on \Twig_Function_Method and \Twig_Filter_Method,
which are both deprecated as of 1.12. Replacing them with the respective
\Twig_SimpleFunction and \Twig_SimpleFilter makes the extension forward-
compatible.

Updates twig extension to work with twig 1.12-2.0

---

Resources/translations/time.de.xliff

It is not correct to say "vor 1 Minute". It should be "vor einer Minute".

Fix the german translation

---

Resources/translations/time.uk.xliff

Fix typo in ukrainian translation.
For past times wrong label for months "мiсяця тому" need to replace to "мiсяцi тому".
For future times translation for months correct.

Fix typo in time.uk.xliff

---

README.md

Thanks to the locale fallback system in Symfony, there is no need to rename these files

Remove useless note from the readme

---

README.md

Some boring updates on docs, do not need any release at all, it's just because using the `%` sign in non-quoted strings in YAML is deprecated.

Update README.md (yml + code)

---

Resources/translations/time.pl.xliff

Current master uses ranges to choose translation to be used in Polish, which is an oversimplification of the rules. For example, it uses "za 43 minut" where it should use "za 43 minuty"
Symfony has a complete set of Polish pluralization rules since at least 2.0 (see: https://github.com/symfony/translation/blob/2.0/PluralizationRules.php ). To use them, you need to simply remove the ranges (and double the string when second and third form are the same - alternatively, we could use `[2,Inf]`).

Fix Polish Translations Pluralization

---

DateTimeFormatter.php

On Symfony 3, the translation does not happen as intended (details in #112). This PR is an alternate proposal to #114. It avoids the deprecation notice for Symfony >=4.2 and uses `transChoice()` for older versions.

Use transChoice for Symfony <4.2

---

Twig/Extension/TimeExtension.php

made a mistake in the previous pr, this should be okay now.
this fixes #125, fixes #122 and makes the bundle work for twig 3.x.
see https://symfony.com/blog/preparing-your-applications-for-twig-3

use namespaced twig classes

---

.travis.yml
DateTimeFormatter.php
Tests/DateTimeFormatterTest.php
Tests/IntegrationTest.php
Tests/fixtures/template.twig
composer.json
phpunit.xml.dist

Follows #127 - we need to get the test suite in order. To do that, it's time to bump to PHP 7.1 and only supported Symfony versions.

bumping php & symfony version dependencies and making code updates

---

DateTimeFormatter.php
DependencyInjection/KnpTimeExtension.php
Resources/config/services.xml
Resources/config/templating.xml
Resources/config/twig.xml
Templating/Helper/TimeHelper.php
Twig/Extension/TimeExtension.php
composer.json

- added DateTimeFormatter::getDatetimeObject()
- deprecated TimeHelper::getDatetimeObject()
- have TimeExtension use DateTimeFormatter directly
- load templating helper only if templating installed
- load twig extension only if twig installed
I was trying to use this bundle as a replacement for the deprecated twig extensions `time_diff` filter. Since `symfony/templating` is deprecated/not recommended I thought it best to remove it as a requirement of this bundle. 
I think there are no BC breaks but let me know if you'd like me to approach this differently.

Remove symfony/templating as a hard dependency

---

README.md

I found this feature really useful and it's not present in the docs, i hope you can accept this PR, it's my first time contributing to a project. 😄

Added bundle usage docs in symfony controllers

---

.travis.yml
README.md
Tests/DateTimeFormatterTest.php
composer.json
phpunit.xml.dist

closes #146 
This PR allows using the bundle with PHP 8.0. 
*Update:*
In order to be compatible I needed to bump the PHPUnit version to `8.5`. This also meant dropping the PHP 7.1 run from Travis as `7.2` is there minimum version. Imo this doesn't hurt as this PHP version is already EOL but there might be other ways using the PHPUnitBridge to work around this if you prefer.
The change in dd3ff7ef4a1c97c2fda0d7007f0f07d9fe30fd65 (dropping global flex plugin in CI run) is unrelated but would otherwise prevent the CI from succeeding. It could also go into another PR if you prefer.

Add compatibility for PHP 8.0

---

CHANGELOG.md

Diff: https://github.com/knplabs/KnpTimeBundle/compare/v1.16.0...v1.16.1
*July 13th, 2021*
- [#158](https://github.com/knplabs/KnpTimeBundle/pull/158) - Fixed strange construction "za dzień" to "jutro" - *@KerbenII*

[release] v1.16.1

---

DateTimeFormatter.php

Remove PHP 8.1 deprecation about DateTime constructor by forcing value `now` as string if parameter is null

Force DateTime constructor parameter (PHP 8.1 deprecation)

---

DateTimeFormatter.php

Risky when the function is_null is overridden.

Replaces is_null with null === $var.

---

DateTimeFormatter.php
Tests/DateTimeFormatterTest.php

I'll use this bundle in an upcoming tutorial... and not needing to pass the `$to` arg would be really nice, and consistent with the Twig extension.

[DX] Make "to" argument optional

---

CHANGELOG.md

*May 10th, 2022*
- [#169](https://github.com/knplabs/knptimebundle/pull/169) - [DX] Make "to" argument optional - *@weaverryan*
_Generated by Git Released_

[git-released] v1.19.0

---

.github/workflows/ci.yaml

Can we change the GitHub Actions to run on forks? Not only in `main` Branch that run needs to be approved.
That would makes life easier for everyone i guess.

[tests] add ci tests for php 8.2, bump github action versions

---

CHANGELOG.md
src/DateTimeFormatter.php
src/Twig/Extension/TimeExtension.php
tests/DateTimeFormatterTest.php
tests/IntegrationTest.php
tests/fixtures/template.twig
translations/time.en.xliff

I have a requirement to use the `Helper::formatDuration()` from `symfony/console` in twig templates. I thought this bundle would be a good place for this.
Copied much of the code from `symfony/console` and added translations. I'll leave to others to add translations for other locales.
```twig
{{ 0|duration }} {# < 1 sec #}
{{ 1|duration }} {# 1 sec #}
{{ 56|duration }} {# 56 secs #}
{{ 60|duration }} {# 1 min #}
```
Should I update the changelog?
For the docs, we should perhaps re-jig them a bit as it says _This bundle does one simple job_ - not anymore if this PR is merged.

feat: add "duration" formatter

---

README.md
composer.json

Requires #177 be merged first.

Doc update for 2.0

---

README.md
tests/IntegrationTest.php
translations/time.en.xliff

Followup to #177. @weaverryan and I concluded it would be best to _not_ use short forms by default.

minor: use long-form duration message for english

---

README.md
src/DateTimeFormatter.php
src/Twig/Extension/TimeExtension.php
translations/time.en.xliff
translations/time.fr.xliff

I add `age` formatter
Examples:
```twig
{# with filter: #}
Age: {{ user.birthdate|age }} 
{# ... or use the equivalent function: #}
Age: {{ age(user.birthdate) }} 
```

feat: add age formatter

---

composer.json

Are there any reasons to not prefer the stable versions over devs one?
This would help to make ci more reliable.

feat: make composer to prefer-stable
